# Generated by Django 2.2.6 on 2019-10-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
                ('visto', models.BooleanField(default=False)),
            ],
        ),
    ]
